### ISSUE TITLE
low level subsetting vs S3 subsetting

### ISSUE THREAD

**Issue by moodymudskipper** [cynkra/struct#4]
Is it acceptable to have struct use low level subsetting, i.e. using `.subset2()` rather than `[[`, or should we fall back to the next method ?

Or should we have 2 classes ?

at the moment `struct(dm::dm(iris))` doesn't even work so I believe the approach is probably inconsistent.

@krlmlr

**Comment by krlmlr** [comment]
At this time, I only care about nested data frames, so `.subset2()` seems sufficient?

**Comment by moodymudskipper** [comment]
With the new version it was easier to use S3 and I think it's better designed that way
